FROM node:alpine 
#도커허브에서 베이스 이미지를 가져옵니다
WORKDIR /app
#해당 어플의 소스코드들이 /app에 들어가게 됩니다
COPY package.json ./
#소스코드가 바뀔 때 마다 종속성을 다시 복사하지 않도록 먼저 작업합니다
RUN npm install
#종속성에 명시된 라이브러리, 프레임워크를 설치합니다
COPY ./ ./
#모든 소스코드를 WORKDIR로 복사합니다
CMD ["npm", "run", "start"]
#컨테이너를 로드할 때 실행할 명령어를 지정합니다